[theme]
primaryColor="#6B4F4F"
backgroundColor="#FAF8F4"
secondaryBackgroundColor="#E8E3D9"
textColor="#2E2E2E"
font ="https://fonts.googleapis.com/css2family=Playwrite+NZ:wght@100..400&family=Roboto:ital,wght@0,100..900;1,100..900&family=Yuyu&display=swap"
